aiopioneer/pioneer_avr.py
After 0.3.0 there is an issue that was introduced when changing the structure of the listening modes where aiopioneer doesn't select the correct ID of a listening mode correctly depending on number of input channels
=> Fix set_listening_mode regression

aiopioneer/commands.py, aiopioneer/parsers/parse.py, aiopioneer/parsers/tuner.py, aiopioneer/pioneer_avr.py
Small PR to add a parser for the SUQ command. Its not supported on many AVRs, but the ones it is supported on this should take away an extra step in needing to configure that and also speed up the calculation of the am frequency step as we're not dependant on increasing and decreasing the frequency.
=> Add query_tuner_am_step command

aiopioneer/commands.py, aiopioneer/pioneer_avr.py
Adds a basic function to set and reset source names. (replicating iControlAV5 functionality)
Source names cannot be longer than 14 characters so a ValueError is raised in the event that a new name is provided longer than 14 chars.
Also, setting the `default` paramter to True will reset the source name to its default value.
=> Add set_source_name function

aiopioneer/pioneer_avr.py
Fix for
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
future.result()  # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in …
=> Fix 'NoneType' object has no attribute 'get'

aiopioneer/pioneer_avr.py
Avoid duplicate checks and loops and follow a simple structure:
1. Update power state and skip all further updates if power is off, since those might not work anyway.
2. Update generic properties that should always be supported.
3. Update everything else that is supported by the respective zone, unless disabled via PARAM_DISABLE_AUTO_QUERY or PARAM_ENABLED_FUNCTIONS.
=> Simplify update_zone logic

aiopioneer/commands.py, aiopioneer/pioneer_avr.py
Prevent sending `query_source_name` command on query_device_info. This method sends all commands beginning with `system_`.
=> Rename command system_query_source_name to query_source_name

aiopioneer/cli.py, aiopioneer/connection.py, aiopioneer/pioneer_avr.py, aiopioneer/properties.py, test_api.py
This change moves AVR properties into a separate class, which prevents non-AVR attributes in the main class from being inadvertently modified by parsers. Params are also moved into a separate class, which will allow parsers to access params.
=> Separate params and AVR properties into separate instantiated classes

aiopioneer/params.py
Don't query volume by default when checking that a zone exists, as it is a poor indicator of whether a zone exists. It causes zones to not be discovered as the volume query command does not respond on all AVRs when the zone is off. Also, virtually all device profiles have enabled this parameter.
If this causes additional zones to be discovered on any AVRs, then a model override can be introduced. Alternatively, the zone can also be configured to be ignored.
=> Change default for PARAM_IGNORE_VOLUME_CHECK to True for all AVRs

aiopioneer/connection.py, aiopioneer/exceptions.py, aiopioneer/pioneer_avr.py, aiopioneer/util.py
* Exception handling has been overhauled:
* More granular exception classes have been added as subclasses of PioneerError class
* AVR errors for connection and update methods raise PioneerError subclasses when an AVR error is encountered.
* `mute_on`, `mute_off`, `set_volume_level` now raises PioneerError subclasses for AVR errors, previously errors were only logged
* `update` raises an ExceptionGroup when multiple exceptions are encountered during a full refresh
* `update` raises `AVRUnavailableError` is raised when the AVR disconnects during a full refresh
* `send_command` always raises `AVRUnavailableError` on AVR disconnect, even when `ignore_error` is set
* Error text interpolation is moved into the PioneerError class
* The responder task has been removed and its functionality merged …
=> Improve Exception Handling

README.md, aiopioneer/pioneer_avr.py
* PioneerAVR.get_listening_modes now returns _list[str]_. This was changed in 0.9.0 but inadvertently omitted from the list of breaking changes
* Update get_listening_modes typing to return list
* Coerce get_listening_modes dict_values to list
* Update documentation for get_listening_modes
=> Update listening modes

README.md, aiopioneer/cli.py, aiopioneer/pioneer_avr.py, python_api.md, test_api.py
* The `PioneerAVR.update` method has been renamed to `refresh` to better reflect what it does
* The `update` CLI command has also been renamed to `refresh` to match the method
=> Rename PioneerAVR.update to refresh

aiopioneer/decoders/system.py
* AVR command `query_system_mcacc_diagnostics` has been renamed to `query_system_mcacc_diagnostic_status`
=> Rename query_system_mcacc_diagnostics to query_system_mcacc_diagnostic_status

aiopioneer/decoders/dsp.py
* AVR commands have been renamed for consistency:
* query_dsp_mcacc_memory_query -> query_dsp_mcacc_memory_set
* query_center_spread -> query_dsp_center_spread
* query_rendering_mode -> query_dsp_rendering_mode
=> Fix DSP code maps

aiopioneer/decoders/tuner.py, aiopioneer/pioneer_avr.py
* AVR commands `set_tuner_band_am` and `set_tuner_band_fm` have been renamed to `tuner_band_am` and `tuner_band_fm` respectively to be consistent with other operational commands
=> Tuner code map updates

aiopioneer/command_queue.py, aiopioneer/decoders/amp.py, aiopioneer/decoders/tuner.py, aiopioneer/pioneer_avr.py, python_api.md
* Commands executed for a zone refresh are now scheduled on the command queue
* The enabled functions configured in PARAM_INITIAL_REFRESH_FUNCTIONS are now run only on initial refresh
* Initial refreshes for a zone are not scheduled if the zone is already pending a refresh
* CommandItem constructor arguments have been renamed:
* `skip_if_startup` has been renamed `skip_if_starting`
* `skip_if_executing` has been repurposed as `skip_if_refreshing` and skips queuing the command if a pending refresh has been set for the zone
=> Queue refresh commands

aiopioneer/decoders/amp.py, aiopioneer/decoders/audio.py, aiopioneer/decoders/code_map.py, aiopioneer/decoders/dsp.py, aiopioneer/decoders/system.py, aiopioneer/decoders/tuner.py, aiopioneer/decoders/video.py, aiopioneer/pioneer_avr.py, aiopioneer/property_registry.py
* Properties have been added to code maps to support auto generating select, number and switch entities in HA for AVR properties
* The system X curve code map has been corrected to match the mapping defined in the FY16 doc
* The video resolution code map has been corrected to use a 2 char code map as defined in the FY16 doc
* System property `speaker_system_raw` has been renamed to `speaker_system_id` for consistency
* AVR command `query_tuner_am_step` has been renamed to `query_tuner_am_frequency_step` to match the property and code map class name
=> Add code map properties for HA

aiopioneer/params.py
* The `video` function has been re-enabled again on the VSX-930
=> Re-enable video queries on VSX-930

README.md, aiopioneer/cli.py, aiopioneer/decoders/audio.py, aiopioneer/exceptions.py, aiopioneer/pioneer_avr.py, aiopioneer/properties.py, python_api.md
* Property `channel_levels` has been renamed to `channel_level`
* PioneerAVR method `set_channel_levels` has been renamed to `set_channel_level`
* AVR commands `set/query_channel_levels` have been renamed to `set/query_channel_level`
=> Rename channel_levels property, PioneerAVR method and AVR commands to channel_level

README.md, aiopioneer/decoders/amp.py, aiopioneer/decoders/system.py
* The values for the `amp.hdmi_out` and `system.external_hdmi_trigger_[12]` properties have been revised to harmonise HDMI port names
=> Harmonise code map HDMI values

aiopioneer/decoders/system.py
* Commands for setting the associated property has been added for system code maps `SurroundPosition`, `XOver`, `XCurve`, `OSDLanguage`, `NetworkStandby`, `ParentalLock`, `ParentalLockPassword`, `HDMIControl`, `HDMIControlMode`, `HDMIArc`, `PQLSForBackup`, `StandbyPassthrough`, `ExternalHDMITrigger1`, `ExternalHDMITrigger2`, `SpeakerBLink`, `OSDOverlay` and `UserLock`
* HA auto entity generation has been enabled for system code maps `SurroundPosition`, `XOver`, `ReEqualisation`, `NetworkDHCP`, `FriendlyName`, `ParentalLockPassword`, `HDMIControl`, `HDMIControlMode`, `HDMIArc`, `PQLSForBackup`, `StandbyPassthrough`, `ExternalHDMITrigger1`, `ExternalHDMITrigger2` and `OSDOverlay`
=> Enable setting of additional system properties

aiopioneer/properties.py, python_api.md
* `PioneerAVR.properties.get_source_list` method has been removed. Use `PioneerAVR.properties.get_source_dict().values()` to retrieve the list of valid sources for a zone
=> Remove get_source_list

aiopioneer/decoders/dsp.py
* Code map `LFEAttenuator` has been converted from a `CodeIntMap` to `CodeDictStrMap` as only certain dB values are valid
=> Convert LFEAttenuator to CodeDictStrMap
